# Generated by Django 5.1.6 on 2025-03-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
