# Generated by Django 5.1.6 on 2025-02-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contacto_alter_productos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='comentario',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
