# Generated by Django 5.1.6 on 2025-03-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_carrito_carritoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carritoproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
