# Generated by Django 5.1.6 on 2025-03-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_carritoproducto_carrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
